In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [4]:
x.shape

(3,)

In [5]:
x.ndim

1

In [6]:
y = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [9]:
y.shape

(3, 3)

In [11]:
y.ndim

2

In [12]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
y.mean()

5.0

In [15]:
y.mean(axis=1)

array([2., 5., 8.])

In [16]:
y.var()

6.666666666666667

In [17]:
y.std()

2.581988897471611

In [18]:
y.max(axis=1)

array([3, 6, 9])

In [19]:
X= np.array([
    [2,3],
    [1,5],
    [3,1]
])

In [20]:
X.T

array([[2, 1, 3],
       [3, 5, 1]])

In [ ]:
np.dot(X,X.T)