In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [3]:
x.shape

(3,)

In [4]:
x.ndim

1

In [5]:
y = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [6]:
y.shape

(3, 3)

In [9]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
y.mean()

5.0

In [14]:
y.mean()

5.0

In [15]:
y.mean(axis = 1)

array([2., 5., 8.])

In [16]:
y.var()

6.666666666666667

In [17]:
y.std

<function ndarray.std>

In [22]:
X = np.array([
      [2,3],
      [1,5],
      [3,1]
])
x

array([1, 2, 3])